### ISSUE TITLE
Fetch only the PV's that correspond to the 3scale PVC's

### ISSUE THREAD

**Issue by avilatusell** [estevaobk/3scaledump#41]
Some customers have a large list of PVs that correspond to other projects and the script takes a long time to execute. The request is to limit the PV's information that the script fetches corresponding only to 3scale.

**Comment by estevaobk** [comment]
Addressed in https://github.com/estevaobk/3scaledump/commit/3b47027c547814f9b778d23a001aeb64465e9aa0
