### ISSUE TITLE
Fetch all the Environment Variables: oc set env dc/<DC> --list

### ISSUE THREAD

**Issue by estevaobk** [estevaobk/3scaledump#50]
Allow us to fetch the environment variables more easily. It could be the case of storing it on `dc/env`.

**Comment by estevaobk** [comment]
Addressed by https://github.com/estevaobk/3scaledump/commit/c5f100021e39ca18c7a26a872ef8b71af057bb5b

**Comment by palmieric** [comment]
@estevaobk do you think that getting all the env through
`oc exec <pod> [-c <container>] env` can be useful?
